Jmlap
conscious-intelligent-labs/xavier-assistant pull request #2
Opened 2019-08-06 02:43 UTC by jatpdubya

Added code for proof of concept and to begin skill building. Currently using PyTTSx3 to talk and SpeechRecognition (only compatible with python up to 3.6.x) using Goggle Web Speak API to listen.

2019-08-07 02:51 UTC, drkfmorton requested changes
Let's move the information in the readme to the wiki. The readme should mostly contain how to deploy, install, and use (provide an example) the code.

2019-08-10 22:53 UTC, drkfmorton reviewed
Let's merge this into dev so I can stay up to date with your changes when I pull dev. This is because we will only clone master to deploy live, which will prevent us from breaking master.

2019-08-10 22:53 UTC, drkfmorton commented on xavier/poc/xavier-start-mimic.py
> +# import pyttsx3
If you are not going to use it. Remove this comment

2019-08-10 22:53 UTC, drkfmorton commented on xavier/poc/xavier-local.py
> +        os.system('/home/jay/git/mimic1/mimic -t "' + audio + '"')
Don't hardcode a path specific to your machine.

2019-08-10 23:15 UTC, jatpdubya commented on xavier/poc/xavier-start-mimic.py
> +# import pyttsx3
I was leaving pyttsx3 for potential to write it in as a backup in case the system isn't running mimic, or mimic install is having issues. I need to just place this kind of code in a separate file for reference as I work on it.

2019-08-10 23:16 UTC, jatpdubya commented on xavier/poc/xavier-local.py
> +        os.system('/home/jay/git/mimic1/mimic -t "' + audio + '"')
Oops. Fixed

2019-08-10 23:18 UTC, jatpdubya commented
Closing to merge into Dev

2019-08-10 23:18 UTC, closed without merging